[google]
type = "service_account"
project_id = "pacific-pride-464016-j9"
private_key_id = "e4640f75a38b2ad9959a01f717a89e825a9969f9"
private_key = '''-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDs52emaQroKTIQ
p8d/KvDU7QhRst58cxQxjHt782UaC38gMglaNzonO7mDjZOf6Egap6saQmk74OjF
+Tf8qREVoHfKlI89nQjKbsgn3mRdnZUyKnVmM8AOt+Qr3SduX0JApFWqOIMN2KAi
z0wzaiUVsCYooz1E8+575s8lZgX0PUCIKYjJYBc7cSGK7L+/PYf215gpp3YKcZwh
lOlF009cAvP+nonJwTNr96++3EIHkqyMfmat5iUiU3LSHse24gEG5Rtqr62MfIKO
iQyFSgtAcRKG5CjYTo9JfUijRHRjCczNnJ3sdgD95YZhh34cN9f7dnO/so6/OhiA
YMaE+LyxAgMBAAECggEAJS+BfoZ4ds6YlDKxxs1HtjRqnOBVufUaU1i4vVEMKpVp
Y/VWsHmAwE3IpdSgOnZscvqkid+owwRfpUukNR2Yl+tzQjIldcdjbNsMwe1Plb45
gAFYIi23VNgakaQKH3IGZT0mUSzDrXW2VSBy1pMvtQLMSo6s/FjJs1scYsNr5dU2
JIT+CmrFJq44kp7IXvlqGyWbmFq2FXe3++4oCFL7FKMsU/UxqVVBJGkzz42vOZsV
+FzB18szwW03bw4xNQg1jjBz2c0Nl1n2o05egg6ABtx4v9SMyrmGxSGGTox8Fkza
chGWW41xYSoG5K8RWZnRc/1TPZrE2pgcbsdfY+b1kQKBgQD+ds6apaEslwJmQgm2
YcJB40j6y81yk4i+IPXpeRj63t5XnOCFcwNog7meEcz9HTD5CHbGiT2w1D49aFGS
3wmC7Zu+KMVfI+IPmyEtqClyGKEYt6Ked6oyEOgtVn23lUYjc3BWSbckEtomGnUi
45KDr20n5/bGJl/cPl2RLFTvFQKBgQDuVXbWkAdLj6sl39wrF2iVH+H2rr9mVMvQ
csslw3HzvhBOECD45zSV4klDGvFjC4WSey1fRvMStlR/JKDg2Rq/sBG+WwCk2gs0
7cGpvzbk0v1As6AXTIBkUm5yuMkpFk7N4vHDQ8lREeGKqlExLCyB6tzk8ReGqmXY
C6q12X1eLQKBgQDbVjkb3+yfbMLqtb19caJp/KmpVAaQ3k6d4/dT+cfoZjasulJl
dQ/ZBMH4WEujWYgfAIaw9xcv1qKXd9XojUu7iWgXbzlBmsJ+xS7CFhMzf7tMfO01
Ptx7L0uR2N2gYpEEebq5Be1QsNdMxL13B0YBMDMclLuHbQhv5WntepLzSQKBgFPA
aLBhkI62/9ehYQcrhK7Ss18ybUQSjETF8illEwgqRCSKemu9I7d/+2q/bw/1Ho0p
B/qxPf3XYL4FKxuYb1PpFXMlG4bSsJl661ExRqMGmcRA2wMU+RFH/lQGJ3puwmaL
V5XcnkQE2pMV4s46zbEhzVoOdsv12TAgeW7J7MpJAoGAAoVSEoU+9meZkAvIWQg8
TGEUPE/oN3qTITLpVbgWKETkcO4olO2lmlbGMstFO6MrSE1xTr9Yop5ndlp79VYa
1nxq8lOndmb3QaLSQluyqeYPEl/F65Z+klwj37PxLJFghO1d74JUvaU3cuJ1qyau
ndzXaykLny+nIQLh8UDKBjs=
-----END PRIVATE KEY-----'''
client_email = "tailortalkintern@pacific-pride-464016-j9.iam.gserviceaccount.com"
client_id = "108593939701719168780"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/tailortalkintern%40pacific-pride-464016-j9.iam.gserviceaccount.com"
calendar_id = "vishnoih10@gmail.com"  # or your specific calendar ID
